apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # my-user  
  db_user: $DB_USER_SECRET
  # my-pass
  db_pwd: $DB_PASS_SECRET
  # my-app-db
  db_name: $DB_NAME_SECRET
  # secret-root-pass
  db_root_pwd: $DB_ROOT_PASS_SECRET
