apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQ2s2WEFWS3R6eVl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeE1qRXlNekUwTURaYUZ3MHpOREV4TVRreU16RTVNRFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURjZE5zYVU5R1E5ZlArKzVRY0hpNFFJeUs3Q29LTlRDRlZIUjZ3QnBnUENxQ2N6TmJNazBqd1pzaHgKZXVxWTZzYk8xVllQakhYUUtKY1hpM2h2UWNvRndveTlFK0JnekRINlFSVG4xbkFBNy9PbUdwYlhiVmt6aVgwWgphVmhyeXRYYS9Qb3JXRk0zdk9tQXFCWGNLbndFOTVTODNUUjMraDA5a2NpUXNFZ0ZhWkx2eFVqVkdwMENmbXAwCnNIenQrdlhEZ3hOamlYUENhd3JpM3Q4WG8zVEcyRHBITFJ6UHlZSno3NGNEbXVkbE4rTTlhc2R5UEwrakJZSjMKY2U5US9mY2IxM1JiMlducTVEeCtVOXZWd3I5M2lmdUxWUFFHcUtoUGhhKzA4bjFHUmxWeTZ3cHZYMEEzWWxsWApYSFRnd0c0K1c3TGh6ZkpjSWFIL2JmaDhobXNsQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTVXJjQzdQWHlNcGlWWE5XTFRORzdVL0h3dTdUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUhTbkd6eWlhNgp6a3VvZWtEZkw4QUZ3bldNaWdjRlIwWGxrQktSMUgycFpkUG1WRmZUMC9nRkNlUVkwUHpZaVFFa3dEbGY2NnVOCmhnYlNJTllxemNwZzF3cGhWSVZxcytZSFlCUnUrQ0doK2RSR2tGZ2ZtK0pUYmRaK1NrWFQyTHVvamNYRzhZT3gKYVBOYmc0MXRxRC83YzJIMFEzZGZ0NUJ6YWpHRkovVVV0bWEwUStiajBTOEhzdnpnSTRja2Z4UUhXSS9BSmRzRQovS1FXRS9CVlJicXdyWGphQnhuWElUL3JZWk8yOXFKdjh3RlpqR2RYOHNwWHUxbjJzNm1wVEdobCsvVWloV2JkClh4VDlCM3FNK1JuRmc4cWNya1Z2cVVaSnl4aXVyMmxHeDkweEZxZTh4UEdyai92VGhNdklUUmZVZ3FHNWRCSHMKdWlkV1dGTFB1STE5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://93E875B48DEB17A5BE149C62EC78FCBA.yl4.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:246826784096:cluster/justin-test-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:246826784096:cluster/justin-test-cluster
    user: arn:aws:eks:us-east-1:246826784096:cluster/justin-test-cluster
  name: arn:aws:eks:us-east-1:246826784096:cluster/justin-test-cluster
current-context: arn:aws:eks:us-east-1:246826784096:cluster/justin-test-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:246826784096:cluster/justin-test-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - justin-test-cluster
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: prod
